// Generated by scripts/generate-protocol-fixtures.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

#include "kegpulse/protocol.hpp"

namespace kegpulse {
namespace fixtures {

struct GoldenVector {
  const char* name;
  char kind;
  const char* request_id;
  const char* operation;
  const kegpulse::Field* fields;
  uint8_t field_count;
  const char* encoded;
};

static constexpr kegpulse::Field k_ping_fields[] = {
    {"nonce", "42"},
};

static constexpr kegpulse::Field k_arm_fields[] = {
    {"boot", "0000000000000001"},
    {"seq", "1"},
    {"sid", "12345678123456781234567812345678"},
    {"ttl", "15000"},
};
static constexpr GoldenVector k_vectors[] = {
    {"ping", 'Q', "12AB34CD", "PING", k_ping_fields, 1, "KP1|Q|12AB34CD|PING|nonce=42*CBA4\n"},
    {"status", 'Q', "00000001", "STATUS", nullptr, 0, "KP1|Q|00000001|STATUS*9E3E\n"},
    {"arm", 'Q', "00000002", "ARM", k_arm_fields, 4, "KP1|Q|00000002|ARM|boot=0000000000000001|seq=1|sid=12345678123456781234567812345678|ttl=15000*82D7\n"},
};
static constexpr size_t k_vector_count = sizeof(k_vectors) / sizeof(k_vectors[0]);

}  // namespace fixtures
}  // namespace kegpulse
