from __future__ import annotations

import argparse
import json
from pathlib import Path


def _identifier(name: str) -> str:
    return "".join(character if character.isalnum() else "_" for character in name.lower())


def render(payload: dict[str, object]) -> str:
    vectors = payload["vectors"]
    if not isinstance(vectors, list):
        raise ValueError("vectors must be a list")
    declarations: list[str] = []
    rows: list[str] = []
    for raw in vectors:
        if not isinstance(raw, dict):
            raise ValueError("each vector must be an object")
        name = _identifier(str(raw["name"]))
        fields = raw["fields"]
        if not isinstance(fields, dict):
            raise ValueError("vector fields must be an object")
        pointer = "nullptr"
        if fields:
            pointer = f"k_{name}_fields"
            declarations.append(f"static constexpr kegpulse::Field {pointer}[] = {{")
            for key, value in fields.items():
                declarations.append(
                    f"    {{{json.dumps(str(key))}, {json.dumps(str(value))}}},"
                )
            declarations.append("};")
            declarations.append("")
        rows.append(
            "    {"
            f"{json.dumps(str(raw['name']))}, "
            f"'{raw['kind']}', "
            f"{json.dumps(str(raw['request_id']))}, "
            f"{json.dumps(str(raw['operation']))}, "
            f"{pointer}, {len(fields)}, {json.dumps(str(raw['encoded']))}"
            "},"
        )
    body = "\n".join(declarations)
    return f"""// Generated by scripts/generate-protocol-fixtures.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

#include "kegpulse/protocol.hpp"

namespace kegpulse {{
namespace fixtures {{

struct GoldenVector {{
  const char* name;
  char kind;
  const char* request_id;
  const char* operation;
  const kegpulse::Field* fields;
  uint8_t field_count;
  const char* encoded;
}};

{body}static constexpr GoldenVector k_vectors[] = {{
{chr(10).join(rows)}
}};
static constexpr size_t k_vector_count = sizeof(k_vectors) / sizeof(k_vectors[0]);

}}  // namespace fixtures
}}  // namespace kegpulse
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate native KP1 golden vectors")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    source = root / "tests" / "fixtures" / "protocol" / "frames.json"
    destination = root / "firmware" / "test" / "test_native" / "protocol_vectors.hpp"
    expected = render(json.loads(source.read_text(encoding="utf-8")))
    if arguments.check:
        if not destination.is_file() or destination.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "protocol_vectors.hpp is stale; run scripts/generate-protocol-fixtures.py"
            )
        return 0
    destination.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
